pipeline {
    agent none

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven'
                    args '--volume /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -DskipTests clean package'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'maven'
                    args '--volume /root/.m2:/root/.m2'
                }
            }
            steps {
                echo 'Testing'
            }
            /*
            sh 'mvn test'
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }*/
        }
        stage('Deploy') {
            agent {
                dockerfile {
                    args '--publish 8080:8080'
                    filename 'Dockerfile'
                }
            }
            steps {
                sh 'docker build --tag my-app .'
                sh 'docker run --publish 8080:8080 my-app'
            }
        }
    }
}